### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by tking16** [MercymeIlya/last-workflow-status#17]
Hello, I've just copied the command from the readme but it seems to be failing to with an exit code 127

```
1s
Run Mercymeilya/last-workflow-status@v0.3.3
Run if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]
Branch name: appium-github-actions-guacamole
Run WORKFLOW_ID=$(curl --header 'authorization: ***' \
/Users/jenkins/actions-runner/_at-tests/_temp/33493bc8-a297-4db6-ab20-262afdd[1](https://github.com/xxxx/actions/runs/4745230288/jobs/8427372214#step:10:1)dd7f.sh: line 3: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15029  100 15029    0     0  37179      0 --:--:-- --:--:-- --:--:-- 37666
curl: (23*** Failed writing body
Error: Process completed with exit code 127.
```

The steps looks as follows:
```
      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
