### ISSUE TITLE
The retrieved workflow is null

### ISSUE THREAD

**Issue by Konubinix** [MercymeIlya/last-workflow-status#19]
When using this step, I get this in the output

`Workflow id: null`

I tried hardcoding the workflow id and running the next bash command and it returns null as well.

Trying with a PAT, I get the correct results.

Therefore, I suppose that this is only a matter of token permission.

Is there anything to do in the settings of the repository to provide the GITHUB_TOKEN the appropriate permission?

**Comment by Konubinix** [comment]
adding the actions permission solved it.

So my job looks like this

```yaml
  CI:
    permissions:
      actions: read # to get the status when trying to slack notify
      contents: read # to checkout the repository
  ...
   steps:
  ...
      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
