### ISSUE TITLE
Status always "null"

### ISSUE THREAD

**Issue by TxHawks** [MercymeIlya/last-workflow-status#6]
With the following:
```yaml
jobs:
  prepare:
    outputs:
      prevStatus: ${{ steps.prevStatus.outputs.last_status }}
    runs-on: ubuntu-latest
    steps:
      - name: Get status of last workflow
        uses: MercymeIlya/last-workflow-status@v0.3
        id: prevStatus
        with:
          - github_token: ${{ secrets.GITHUB_TOKEN }}
```

`steps.prevStatus.outputs.last_status` is always `null`.

Not sure what I'm doing wrong
